version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: proyectocamara_postgres
    restart: always
    environment:
      POSTGRES_DB: ProyectoCamara
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
     - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
